### ISSUE TITLE
Option argument is not optional

### ISSUE THREAD

**Issue by edkek** [BitskiCo/bitski-node#3]
When creating a new provider, you must specify the option parameter even if you dont provide any options. This is contradicting to what the README says

For example:
```
const provider = Bitski.getProvider("YOUR CLIENT ID");
```
The above code snippet results in the following error
```
/root/war-riders-preorder/backend-&-contract/node_modules/bitski-node/dist/index.js:15    

const tokenProvider = new credential_token_provider_1.default(options.credentials || {}, {});

TypeError: Cannot read property 'credentials' of undefined    
    at Object.getProvider (/root/war-riders-preorder/backend-&-contract/node_modules/bitski-node/dist/index.js:15:75)   
    at Object.<anonymous> (/root/war-riders-preorder/backend-&-contract/index.js:60:33)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)    
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
```

However, this error can be avoided by simply providing an empty object as a second parameter
```
const provider = Bitski.getProvider("YOUR CLIENT ID", {});
```

The README should be updated, or the second parameter should be optional. I think making the second parameter optional makes the most sense since providing an empty object does seem to work

**Comment by pixelmatrix** [comment]
Thanks for reporting this @edkek. It should definitely be optional, that was just an oversight. I'll get a fix out today.
